import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Link } from 'react-router-dom'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="p-4 bg-blue-400 w-full">
          <span>logo</span>
          <ul>
            {/* <li><Link href="/about"></Link></li> */}
            <li>link 2</li>
            <li>link 3</li>
          </ul>
        </nav>
        <div className="container mx-auto">{children}</div>
      </body>
    </html>
  )
}
